// LED
// You can call pmu_set_led1_value(1) function to turn it on

// Vibrator
#define VIBRATOR_GPIO_PIN_NAME GPIO_PORT_C
#define VIBRATOR_GPIO_PIN_NUM GPIO_BIT_5
#define VIBRATOR_GPIO_PIN_FUNC PORTC5_FUNC_C5

// Button
#define BUTTON_GPIO_PIN_NAME GPIO_PORT_A
#define BUTTON_GPIO_PIN_NUM GPIO_BIT_1
#define BUTTON_GPIO_PIN_FUNC PORTA1_FUNC_A1

// Display
// Reset
#define DISPLAY_RESET_PIN_NAME GPIO_PORT_A
#define DISPLAY_RESET_PIN_NUM GPIO_BIT_0
#define DISPLAY_RESET_PIN_FUNC PORTA0_FUNC_A0

// SDA
#define DISPLAY_SDA_PIN_NAME GPIO_PORT_A
#define DISPLAY_SDA_PIN_NUM GPIO_BIT_6
#define DISPLAY_SDA_PIN_FUNC PORTA6_FUNC_SSP0_DOUT

// SCL
#define DISPLAY_SCL_PIN_NAME GPIO_PORT_A
#define DISPLAY_SCL_PIN_NUM GPIO_BIT_4
#define DISPLAY_SCL_PIN_FUNC PORTA4_FUNC_SSP0_CLK

// CS
#define DISPLAY_CS_PIN_NAME GPIO_PORT_A
#define DISPLAY_CS_PIN_NUM GPIO_BIT_5
#define DISPLAY_CS_PIN_FUNC PORTA5_FUNC_A5

// DC
#define DISPLAY_DC_PIN_NAME GPIO_PORT_A
#define DISPLAY_DC_PIN_NUM GPIO_BIT_7
#define DISPLAY_DC_PIN_FUNC PORTA7_FUNC_A7

// BACKLIGHT
// You can call pmu_set_led2_value(1) function to turn it on